//! `#[derive(Connected)]` codegen — route introspection helpers.
//!
//! Emits two functions from the `Route` enum:
//!
//! - `pub fn route_account_id(route: &Route) -> Option<&str>` — returns the
//!   `account_id` field of account-scoped variants. Variants that have an
//!   `account_id` field but carry `#[connected(skip_account_id)]` get `None`
//!   (e.g. `ReauthAccount` — reauth must not be treated as targeting a known
//!   account).
//!
//! - `#[cfg(debug_assertions)] fn route_variant_name(route: &Route) -> &'static str`
//!   — short discriminant name used by the dev-mode route-coverage counter.
//!
//! The derive replaces two hand-maintained `match` blocks in `routes.rs` that
//! drifted from the `Route` enum.  Any new variant automatically participates
//! after a recompile.

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{Data, DeriveInput, Fields, Variant};

/// Walk the variants of the annotated enum and emit the two introspection fns.
pub fn expand(input: TokenStream) -> TokenStream {
    let ast: DeriveInput = match syn::parse(input) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error().into(),
    };

    let enum_name = &ast.ident;

    let variants: Vec<&Variant> = match &ast.data {
        Data::Enum(e) => e.variants.iter().collect(),
        _ => {
            return syn::Error::new(
                Span::call_site(),
                "#[derive(Connected)] can only be applied to enums",
            )
            .to_compile_error()
            .into();
        }
    };

    // ── route_account_id arms ────────────────────────────────────────────────
    let mut some_arms = Vec::new(); // variants that yield Some(account_id)
    let mut none_arms = Vec::new(); // variants that yield None (no field or skip)

    for v in &variants {
        let vname = &v.ident;
        let has_account_id = variant_has_account_id_field(v);
        let skip = variant_has_skip_account_id_attr(v);

        if has_account_id && !skip {
            some_arms.push(quote! {
                #enum_name::#vname { account_id, .. } => ::core::option::Option::Some(account_id.as_str()),
            });
        } else {
            match &v.fields {
                Fields::Unit => none_arms.push(quote! { #enum_name::#vname => ::core::option::Option::None, }),
                _ => none_arms.push(quote! { #enum_name::#vname { .. } => ::core::option::Option::None, }),
            }
        }
    }

    // ── route_variant_name arms (debug_assertions only) ─────────────────────
    let variant_name_arms: Vec<_> = variants
        .iter()
        .map(|v| {
            let vname = &v.ident;
            let vname_str = vname.to_string();
            match &v.fields {
                Fields::Unit => quote! { #enum_name::#vname => #vname_str, },
                _ => quote! { #enum_name::#vname { .. } => #vname_str, },
            }
        })
        .collect();

    // ── ReauthAccount comment ────────────────────────────────────────────────
    // The `#[allow(clippy::match_same_arms)]` is needed because ReauthAccount
    // lands in the `None` group even though it has an account_id field (by
    // design — see the `#[connected(skip_account_id)]` annotation on that
    // variant).  Without the allow, clippy may collapse the None arms.

    let expanded = quote! {
        /// Return the account id encoded by an account-scoped route, if any.
        ///
        /// Generated by `#[derive(Connected)]` from field inspection.
        /// Variants with an `account_id` field yield `Some`; those without, or
        /// those annotated `#[connected(skip_account_id)]`, yield `None`.
        #[must_use]
        // lint-allow-unused: match_same_arms — ReauthAccount intentionally
        // returns None despite having account_id (skip_account_id annotation).
        #[allow(clippy::match_same_arms)]
        pub fn route_account_id(route: &Self) -> ::core::option::Option<&str> {
            match route {
                #(#some_arms)*
                #(#none_arms)*
            }
        }

        /// Short discriminant name for a `Route` value.
        ///
        /// Generated by `#[derive(Connected)]`.  Used only by the
        /// debug-assertions route-coverage counter; no runtime consumer in
        /// release builds.
        #[cfg(debug_assertions)]
        fn route_variant_name(route: &Self) -> &'static str {
            match route {
                #(#variant_name_arms)*
            }
        }
    };

    // Wrap in an inherent `impl` block so the fns live on the enum.
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();
    let final_output = quote! {
        impl #impl_generics #enum_name #ty_generics #where_clause {
            #expanded
        }
    };

    final_output.into()
}

// ── helpers ──────────────────────────────────────────────────────────────────

/// Returns `true` if any named field in `v` is called `account_id`.
fn variant_has_account_id_field(v: &Variant) -> bool {
    match &v.fields {
        Fields::Named(named) => named
            .named
            .iter()
            .any(|f| f.ident.as_ref().map_or(false, |i| i == "account_id")),
        _ => false,
    }
}

/// Returns `true` if the variant has `#[connected(skip_account_id)]` in its
/// attributes.  This is the escape hatch for variants like `ReauthAccount`
/// that carry an `account_id` field but must not be treated as targeting a
/// known active account.
fn variant_has_skip_account_id_attr(v: &Variant) -> bool {
    for attr in &v.attrs {
        if !attr.path().is_ident("connected") {
            continue;
        }
        // Parse the token-tree inside `#[connected(...)]` to look for the
        // `skip_account_id` ident anywhere in the list.
        let tokens = match attr.meta.require_list() {
            Ok(l) => l.tokens.clone(),
            Err(_) => continue,
        };
        // Walk through comma-separated idents.
        let tokens_str = tokens.to_string();
        if tokens_str.contains("skip_account_id") {
            return true;
        }
    }
    false
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use quote::quote;
    use syn::parse_quote;

    #[test]
    fn unit_variant_yields_none_arm() {
        let v: Variant = parse_quote! { Root };
        assert!(!variant_has_account_id_field(&v));
        assert!(!variant_has_skip_account_id_attr(&v));
    }

    #[test]
    fn variant_with_account_id_field_detected() {
        let v: Variant = parse_quote! {
            DmsHome { backend: String, instance_id: String, account_id: String }
        };
        assert!(variant_has_account_id_field(&v));
        assert!(!variant_has_skip_account_id_attr(&v));
    }

    #[test]
    fn variant_with_skip_account_id_attr() {
        let v: Variant = parse_quote! {
            #[connected(linked, skip_account_id)]
            ReauthAccount { backend: String, instance_id: String, account_id: String }
        };
        assert!(variant_has_account_id_field(&v));
        assert!(variant_has_skip_account_id_attr(&v));
    }

    #[test]
    fn variant_without_account_id_field() {
        let v: Variant = parse_quote! {
            SettingsRoute
        };
        assert!(!variant_has_account_id_field(&v));
    }

    #[test]
    fn full_enum_expand_compiles() {
        // Just verify expand doesn't panic/error on a minimal enum.
        let ts: proc_macro2::TokenStream = quote! {
            enum Route {
                #[connected(entry_point)]
                Root,
                #[connected(linked)]
                DmsHome { account_id: String, backend: String },
                #[connected(linked, skip_account_id)]
                ReauthAccount { account_id: String, backend: String },
            }
        };
        // expand takes a proc_macro::TokenStream — we can't call it directly in
        // unit tests (proc_macro types aren't available outside macro context).
        // Test the helpers only.
        let ast: DeriveInput = syn::parse2(ts).unwrap();
        let vars: Vec<&Variant> = match &ast.data {
            Data::Enum(e) => e.variants.iter().collect(),
            _ => panic!("expected enum"),
        };
        assert_eq!(vars.len(), 3);
        // Root
        assert!(!variant_has_account_id_field(vars[0]));
        // DmsHome
        assert!(variant_has_account_id_field(vars[1]));
        assert!(!variant_has_skip_account_id_attr(vars[1]));
        // ReauthAccount
        assert!(variant_has_account_id_field(vars[2]));
        assert!(variant_has_skip_account_id_attr(vars[2]));
    }
}
