//! Build script for poly-core.
//!
//! Concatenates all CSS partials from `assets/styling/` into `assets/tailwind.css`
//! so that `asset!("assets/tailwind.css")` in `src/ui/mod.rs` picks up the full
//! stylesheet without any changes to the Rust code.
//!
//! To edit styles, modify the individual files inside `assets/styling/`.
//! Do NOT edit `assets/tailwind.css` directly — it is overwritten on every build.
//!
//! Cascade order is determined by the `PARTIALS` array below.

use std::path::Path;

/// CSS partials to concatenate, in cascade order.
///
/// The order matches how they were originally laid out in tailwind.css:
/// reset/variables first, then structural layout, then component-specific styles.
const PARTIALS: &[&str] = &[
    "variables.css",          // CSS custom properties — theme tokens
    "layout.css",             // Base styles, layout grid, window chrome, voice banner
    "sidebar.css",            // Server sidebar, account server bar, status dots
    "channel-list.css",       // Channel list
    "chat.css",               // Chat view (messages, input, attachments, reactions)
    "user-sidebar.css",       // User/member sidebar, DM header, notification indicators
    "settings-layout.css",    // Settings page layout shell
    "settings-content.css",   // Settings pages (accounts, plugins, profile, language)
    "search.css",             // Global search page
    "wizard.css",             // Setup wizard, buttons, forms, reply UI
    "theme-utils.css",        // Backup wizard, scrollbar, theme settings, responsive
    "voice-channel.css",      // Voice/video channel view, voice bar
    "voice-settings.css",     // Voice settings popup/page, voice controls, account footer
    "account-shell.css",      // Presence picker, account switcher, view shell
    "toolbar.css",            // Emoji picker, hover actions, input toolbar, file drag
    "dm-pages.css",           // DM nav, search bars, voice+notif settings, friends panel
    "server-settings.css",    // Context menu, server settings, diagnostics
    "account-profile.css",    // Account profile popup, slash command autocomplete
    "account-forms.css",      // Add account, create server / channel forms
    "mobile-shell.css",       // Force-mobile / narrow-viewport shell overrides
    "user-profile-modal.css", // Unified user profile modal (global overlay)
    "direct-call-overlay.css", // Route-backed pending direct-call overlay
    "media-viewer.css",       // Route-backed fullscreen message media viewer
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let crate_root = Path::new(&manifest_dir);
    let styling_dir = crate_root.join("assets").join("styling");
    let out_path = crate_root.join("assets").join("tailwind.css");

    // Tell Cargo to re-run this build script if any partial changes.
    for partial in PARTIALS {
        println!("cargo:rerun-if-changed=assets/styling/{}", partial);
    }
    // Also re-run if the build script itself changes.
    println!("cargo:rerun-if-changed=build.rs");

    // Concatenate all partials.
    let mut output = String::with_capacity(400_000);
    output.push_str(
        "/* Poly — Main Stylesheet\n\
         \n\
         \x20  AUTO-GENERATED by crates/core/build.rs — DO NOT EDIT THIS FILE.\n\
         \x20  Edit the individual files in assets/styling/ instead.\n\
         \n\
         \x20  Partials (in cascade order):\n",
    );
    for partial in PARTIALS {
        output.push_str(&format!("     assets/styling/{partial}\n"));
    }
    output.push_str(
        "   ======================================================================= */\n\n",
    );

    for partial in PARTIALS {
        let path = styling_dir.join(partial);
        let content = std::fs::read_to_string(&path)
            .map_err(|e| format!("build.rs: failed to read {}: {e}", path.display()))?;
        output.push_str(&content);
        output.push('\n');
    }

    // Only write if the content actually changed — avoids unnecessary rebuilds.
    let write_needed = match std::fs::read_to_string(&out_path) {
        Ok(existing) => existing != output,
        Err(_) => true,
    };
    if write_needed {
        std::fs::write(&out_path, &output)
            .map_err(|e| format!("build.rs: failed to write tailwind.css: {e}"))?;
    }

    Ok(())
}
