//! Build script for poly-core.
//!
//! **Release builds:** Concatenates all CSS partials from `assets/styling/` into
//! `assets/tailwind.css` and generates `css.rs` with a single asset reference.
//!
//! **Debug / non-release builds:** Generates `css.rs` with individual `asset!()`
//! references for each CSS partial. `tailwind.css` is not created (and is deleted
//! if it exists). This keeps AI coding agents from reading or editing the giant
//! concatenated file during development.
//!
//! To edit styles, modify the individual files inside `assets/styling/`.
//! Do NOT edit `assets/tailwind.css` directly — it is overwritten on every
//! release build.

use std::path::Path;

/// CSS partials to include, in cascade order.
///
/// The order matches how they were originally laid out in tailwind.css:
/// reset/variables first, then structural layout, then component-specific styles.
const PARTIALS: &[&str] = &[
    "variables.css",           // CSS custom properties — theme tokens
    "layout.css",              // Base styles, layout grid, window chrome, voice banner
    "sidebar.css",             // Server sidebar, account server bar, status dots
    "channel-list.css",        // Channel list
    "chat.css",                // Chat view (messages, input, attachments, reactions)
    "user-sidebar.css",        // User/member sidebar, DM header, notification indicators
    "settings-layout.css",     // Settings page layout shell
    "settings-content.css",    // Settings pages (accounts, plugins, profile, language)
    "search.css",              // Global search page
    "wizard.css",              // Setup wizard, buttons, forms, reply UI
    "theme-utils.css",         // Backup wizard, scrollbar, theme settings, responsive
    "voice-channel.css",       // Voice/video channel view, voice bar
    "voice-settings.css",      // Voice settings popup/page, voice controls, account footer
    "account-shell.css",       // Presence picker, account switcher, view shell
    "toolbar.css",             // Emoji picker, hover actions, input toolbar, file drag
    "dm-pages.css",            // DM nav, search bars, voice+notif settings, friends panel
    "server-settings.css",     // Context menu, server settings, diagnostics
    "account-profile.css",     // Account profile popup, slash command autocomplete
    "account-forms.css",       // Add account, create server / channel forms
    "mobile-shell.css",        // Force-mobile / narrow-viewport shell overrides
    "user-profile-modal.css",  // Unified user profile modal (global overlay)
    "direct-call-overlay.css", // Route-backed pending direct-call overlay
    "media-viewer.css",        // Route-backed fullscreen message media viewer
    "code-explorer.css",       // GitHub / code-channel two-pane explorer
    "server-overview.css",     // Forge backend repo/server overview landing page
    "client-view.css",         // Plugin-declared non-chat view (list/card/tree/split body, toolbar, header)
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")?;
    let crate_root = Path::new(&manifest_dir);
    let styling_dir = crate_root.join("assets").join("styling");
    // Write css.rs next to src/ui/mod.rs so Dioxus can track it for hot-reload.
    let css_rs_path = crate_root.join("src").join("ui").join("css.rs");
    let tailwind_path = crate_root.join("assets").join("tailwind.css");

    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let is_release = profile == "release";

    // Tell Cargo to re-run this build script if any partial changes.
    for partial in PARTIALS {
        println!("cargo:rerun-if-changed=assets/styling/{}", partial);
    }
    // Also watch the themes directory for changes.
    println!("cargo:rerun-if-changed=assets/styling/themes");
    // Also re-run if the build script itself changes.
    println!("cargo:rerun-if-changed=build.rs");
    // Also re-run if css.rs is deleted (e.g., after a git clean).
    println!("cargo:rerun-if-changed=src/ui/css.rs");

    // Bake locale FTL content DIRECTLY into the generated file (not via
    // an indirect include_str!). The previous generation emitted 4 static
    // `include_str!` lines whose text never changed regardless of FTL
    // content, defeating the write-triggers-recompile mechanism. By
    // embedding the literal FTL content here, every FTL edit produces a
    // new baked_locales.rs body, forcing the i18n module to recompile.
    let workspace_root = crate_root.join("..").join("..");
    let locales_dir = workspace_root.join("locales");
    let baked_path = crate_root.join("src").join("i18n").join("baked_locales.rs");
    let mut baked = String::from(
        "// AUTO-GENERATED by crates/core/build.rs — DO NOT EDIT.\n\
         // Changes to workspace locales/<locale>/main.ftl regenerate this file.\n\n",
    );
    for locale in ["en", "de", "es", "fr"] {
        let path = locales_dir.join(locale).join("main.ftl");
        let canonical = std::fs::canonicalize(&path)
            .map_err(|e| format!("build.rs: locales/{locale}/main.ftl: {e}"))?;
        println!("cargo:rerun-if-changed={}", canonical.display());
        let content = std::fs::read_to_string(&canonical)
            .map_err(|e| format!("build.rs: read {}: {e}", canonical.display()))?;
        // Use a raw string literal with enough # to defeat any embedded
        // `"#` sequences in the FTL source.
        let mut pound_fence = String::from("#");
        while content.contains(&format!("\"{pound_fence}")) {
            pound_fence.push('#');
        }
        baked.push_str(&format!(
            "pub(super) const FTL_{}: &str = r{pound_fence}\"{content}\"{pound_fence};\n\n",
            locale.to_uppercase(),
        ));
    }
    // Only write when the body actually changed — avoids churning mtimes
    // when nothing relevant moved.
    let prev = std::fs::read_to_string(&baked_path).unwrap_or_default();
    if prev != baked {
        std::fs::write(&baked_path, baked)
            .map_err(|e| format!("build.rs: write baked_locales.rs: {e}"))?;
    }

    if is_release {
        // ── Release build: concatenate into tailwind.css + single asset ──

        let mut output = String::with_capacity(400_000);
        output.push_str(
            "/* Poly — Main Stylesheet\n\
             \n\
             \x20  AUTO-GENERATED by crates/core/build.rs — DO NOT EDIT THIS FILE.\n\
             \x20  Edit the individual files in assets/styling/ instead.\n\
             \n\
             \x20  Partials (in cascade order):\n",
        );
        for partial in PARTIALS {
            output.push_str(&format!("     assets/styling/{partial}\n"));
        }
        output.push_str(
            "   ======================================================================= */\n\n",
        );

        for partial in PARTIALS {
            let path = styling_dir.join(partial);
            let content = std::fs::read_to_string(&path)
                .map_err(|e| format!("build.rs: failed to read {}: {e}", path.display()))?;
            output.push_str(&content);
            output.push('\n');
        }

        // Only write if the content actually changed — avoids unnecessary rebuilds.
        let write_needed = match std::fs::read_to_string(&tailwind_path) {
            Ok(existing) => existing != output,
            Err(_) => true,
        };
        if write_needed {
            std::fs::write(&tailwind_path, &output)
                .map_err(|e| format!("build.rs: failed to write tailwind.css: {e}"))?;
        }

        // Generate css.rs with a single asset in a static slice.
        let css_rs = r#"// AUTO-GENERATED by crates/core/build.rs — DO NOT EDIT.
const CSS_0: Asset = asset!("assets/tailwind.css");
const CSS_SLICES: &[Asset] = &[CSS_0];
"#;
        std::fs::write(&css_rs_path, css_rs)
            .map_err(|e| format!("build.rs: failed to write css.rs: {e}"))?;
    } else {
        // ── Debug / non-release build: individual CSS assets ──

        // Remove tailwind.css if it exists (cleanup from a previous release build).
        if tailwind_path.exists() {
            drop(std::fs::remove_file(&tailwind_path));
        }

        // Generate css.rs with individual asset!() references for each partial.
        let mut css_rs = String::from(
            "// AUTO-GENERATED by crates/core/build.rs — DO NOT EDIT.\n\
             // Debug build — individual CSS files loaded separately.\n\n",
        );

        for (i, partial) in PARTIALS.iter().enumerate() {
            let const_name = format!("CSS_{}", i);
            css_rs.push_str(&format!(
                "const {const_name}: Asset = asset!(\"assets/styling/{partial}\");\n"
            ));
        }

        // Generate a CSS_SLICES constant for easy iteration.
        css_rs.push_str("\nconst CSS_SLICES: &[Asset] = &[\n");
        for i in 0..PARTIALS.len() {
            css_rs.push_str(&format!("    CSS_{i},\n"));
        }
        css_rs.push_str("];\n");

        std::fs::write(&css_rs_path, css_rs)
            .map_err(|e| format!("build.rs: failed to write css.rs: {e}"))?;
    }

    Ok(())
}
